server:
  port: 8002
  servlet:
    context-path: /search

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: search-provider

  elasticsearch:
    rest:
      uris: 172.20.97.67:9200
      connection-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"