server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Anfield613/springcloud-config
          username: fausto0613@outlook.com
          password: fausto@100804
          search-paths: springcloud-config
      label: master

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka