server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment_route
        uri: lb://payment
        predicates:
        - Path=/payment/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.fill.springcloud: debug
