server:
  port: 8003
  servlet:
    context-path: /payment
spring:
  application:
    name: payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

logging:
  level:
    com.fill.springcloud: debug
