server:
  port: 7001

spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
