server:
  port: 8002

spring:
  application:
    name: filestorage-server
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${eureka.client.eureka-server-port}/eureka
    eureka-server-port: 7001
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

logging:
  level:
    com.fill.filestorage: debug


